name: pmtiles_cli
description: A simple CLI for using pmtiles.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.4

dependencies:
  args: ^2.4.2
  pmtiles: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
