name: pmtiles_cli
description: A simple CLI for using pmtiles.
version: 1.1.0
publish_to: none

environment:
  sdk: ^3.11.3

resolution: workspace

dependencies:
  args: ^2.6.0
  pmtiles: ^2.0.0

dev_dependencies:
  test: ^1.25.2
