name: pmtiles

ide:
  intellij: false

packages:
  - packages/*

scripts:
  test:
    run: melos run test:dart --no-select

  test:dart:
    description: Run `dart test` in all dart packages.
    run: dart test
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      flutter: false
      dirExists: test

  pmtiles:
    description: Run the pmtiles CLI binary.
    run: dart run packages/pmtiles_cli/bin/pmtiles.dart

  upgrade:
    run: |
      melos exec -- \
        "dart pub outdated && dart pub upgrade --major-versions --tighten"
      melos clean
      melos bootstrap
    description: |
      Upgrade all packages to the latest version.
