name: pmtiles
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

dependencies:
  # Maybe overkill to use this package, but anyone consuming this package
  # is most likely already using it.
  latlong2: ^0.9.0

  # I only need CodedBufferReader from this package, but it's very useful for
  # reading varints.
  meta: ^1.11.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
