name: pmtiles
description:
  A library for parsing Protomaps PMTiles files. A single file archive format
  for storing raster or vector map tiles.
version: 1.1.0
repository: https://github.com/bramp/pmtiles-dart

environment:
  sdk: ^3.1.4

dependencies:
  collection: ^1.18.0
  http: ^1.1.0
  meta: ^1.10.0
  path: ^1.8.3

  # latlong2 is maybe overkill, but anyone consuming this package is most likely already using it.
  latlong2: ^0.9.0

  # I only need CodedBufferReader from the protobuf package, because it's very useful for
  # reading varints.
  protobuf: ^3.1.0

  pool: 1.5.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  trotter: 2.2.0
