name: pmtiles_tests
description: Integration tests for pmtiles
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.4
  flutter: ">=1.17.0"

# We don't actually need flutter, but this is a useful way to ensure
# we don't conflict with any pinned dependencies.
# https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  lints: ^3.0.0
  http: ^1.2.0
  path: ^1.8.3
  pmtiles: ^1.2.0
  stream_channel: ^2.1.2
