name: pmtiles_tests
description: Integration tests for pmtiles
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.1.0
  path: ^1.8.3
  pmtiles: ^1.1.0
