# To test this workflow, you can use the following command:
# act -j build -s GITHUB_TOKEN="$(gh auth token)" --container-architecture linux/amd64
name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache default Flutter artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache/
            /opt/hostedtoolcache/flutter/
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter doctor -v

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: make format

      - name: Analyze project source
        run: make analyze

      # Needed for the integration tests
      - name: Install http-server
        run: npm install http-server

      # Needed for the integration tests
      - name: Install pmtiles
        # Running from HEAD as it has a fix we need
        # https://github.com/jaxxstorm/action-install-gh-release/commit/410ab39896b55ae0084c2b3921e25665356169b6
        # switch to a tagged version when it's released
        uses: jaxxstorm/action-install-gh-release@HEAD
        with:
          repo: protomaps/go-pmtiles
          tag: v1.14.0 # Pinned version (to make the tests less flakey)

      - run: pmtiles version

      - name: Run tests (dart)
        run: make test-dart

      - name: Run tests (flutter)
        run: make test-flutter

      - name: Run tests (node)
        run: make test-node

      - name: Run tests (chrome)
        run: make test-chrome
